export type Word = {
  word: string;
  clue: string;
};

export const INITIAL_WORDS: Word[] = [
  { word: "soleil", clue: "Astre qui nous éclaire le jour" },
  { word: "fromage", clue: "Produit laitier souvent associé au vin" },
  { word: "chocolat", clue: "Gourmandise sucrée à base de cacao" },
  { word: "croissant", clue: "Viennoiserie en forme de lune" },
  { word: "voyage", clue: "Action de se déplacer vers un lieu lointain" },
  { word: "musique", clue: "Art de combiner les sons" },
  { word: "jardin", clue: "Espace où l'on cultive des plantes" },
  { word: "livre", clue: "Ensemble de pages imprimées et reliées" },
  { word: "montagne", clue: "Élévation naturelle du terrain" },
  { word: "rivière", clue: "Cours d'eau naturel" },
  { word: "ordinateur", clue: "Machine pour traiter l'information" },
  { word: "téléphone", clue: "Appareil pour communiquer à distance" },
  { word: "voiture", clue: "Véhicule automobile à quatre roues" },
  { word: "maison", clue: "Bâtiment servant d'habitation" },
  { word: "arbre", clue: "Végétal avec un tronc et des branches" },
  { word: "fleur", clue: "Partie colorée et odorante d'une plante" },
  { word: "plage", clue: "Étendue de sable au bord de la mer" },
  { word: "ciel", clue: "Espace visible au-dessus de la Terre" },
  { word: "étoile", clue: "Astre qui brille dans la nuit" },
  { word: "lune", clue: "Satellite naturel de notre planète" },
  { word: "cuisine", clue: "Pièce où l'on prépare les repas" },
  { word: "chaise", clue: "Siège avec un dossier pour une personne" },
  { word: "table", clue: "Meuble pour manger ou travailler" },
  { word: "fourchette", clue: "Couvert pour piquer les aliments" },
  { word: "couteau", clue: "Ustensile tranchant pour couper" },
  { word: "verre", clue: "Récipient transparent pour boire" },
  { word: "fenêtre", clue: "Ouverture vitrée dans un mur" },
  { word: "porte", clue: "Panneau mobile pour fermer une ouverture" },
  { word: "lit", clue: "Meuble sur lequel on dort" },
  { word: "rêve", clue: "Histoire que l'on se fait en dormant" },
  { word: "amour", clue: "Sentiment d'affection très fort" },
  { word: "amitié", clue: "Lien d'affection entre personnes" },
  { word: "famille", clue: "Ensemble des parents et enfants" },
  { word: "travail", clue: "Activité professionnelle rémunérée" },
  { word: "école", clue: "Lieu où l'on apprend" },
  { word: "vacances", clue: "Période de repos, sans travail" },
  { word: "sport", clue: "Activité physique et de loisir" },
  { word: "cinéma", clue: "Art de faire des films" },
  { word: "théâtre", clue: "Lieu de représentation de pièces" },
  { word: "danse", clue: "Mouvement du corps en rythme" },
  { word: "peinture", clue: "Art d'appliquer des couleurs" },
  { word: "sculpture", clue: "Art de modeler ou tailler la matière" },
  { word: "poésie", clue: "Art du langage et des vers" },
  { word: "forêt", clue: "Grande étendue couverte d'arbres" },
  { word: "désert", clue: "Région aride avec peu de végétation" },
  { word: "océan", clue: "Vaste étendue d'eau salée" },
  { word: "île", clue: "Terre entourée d'eau" },
  { word: "volcan", clue: "Montagne qui crache du feu" },
  { word: "grotte", clue: "Cavité naturelle dans la roche" },
  { word: "cascade", clue: "Chute d'eau naturelle" },
  { word: "brouillard", clue: "Nuage très bas qui touche le sol" },
  { word: "neige", clue: "Précipitation de cristaux de glace" },
  { word: "orage", clue: "Perturbation avec éclairs et tonnerre" },
  { word: "arc-en-ciel", clue: "Phénomène optique après la pluie" },
  { word: "planète", clue: "Astre en orbite autour d'une étoile" },
  { word: "galaxie", clue: "Ensemble de milliards d'étoiles" },
  { word: "cerveau", clue: "Organe de la pensée" },
  { word: "cœur", clue: "Organe qui pompe le sang" },
  { word: "main", clue: "Partie du corps pour saisir" },
  { word: "œil", clue: "Organe de la vision" },
  { word: "sourire", clue: "Expression de joie du visage" },
  { word: "rire", clue: "Son exprimant la gaieté" },
  { word: "larme", clue: "Goutte d'eau salée de l'œil" },
  { word: "silence", clue: "Absence de bruit" },
  { word: "temps", clue: "Ce qui passe, les heures, les jours..." },
  { word: "histoire", clue: "Récit d'événements passés" },
  { word: "futur", clue: "Ce qui n'est pas encore arrivé" },
  { word: "liberté", clue: "État de ne pas être contraint" },
  { word: "paix", clue: "Absence de guerre ou de conflit" },
  { word: "guerre", clue: "Lutte armée entre États" },
  { word: "pont", clue: "Construction pour franchir un obstacle" },
  { word: "route", clue: "Voie aménagée pour la circulation" },
  { word: "train", clue: "Moyen de transport sur rails" },
  { word: "avion", clue: "Appareil qui vole dans les airs" },
  { word: "bateau", clue: "Construction flottante pour naviguer" },
  { word: "vélo", clue: "Moyen de transport à deux roues" },
  { word: "miroir", clue: "Surface qui réfléchit l'image" },
];
