export type Word = {
  word: string;
  clue: string;
};

export const INITIAL_WORDS: Word[] = [
  { word: "soleil", clue: "Astre qui nous éclaire le jour" },
  { word: "fromage", clue: "Produit laitier souvent associé au vin" },
  { word: "chocolat", clue: "Gourmandise sucrée à base de cacao" },
  { word: "croissant", clue: "Viennoiserie en forme de lune" },
  { word: "voyage", clue: "Action de se déplacer vers un lieu lointain" },
  { word: "musique", clue: "Art de combiner les sons" },
  { word: "jardin", clue: "Espace où l'on cultive des plantes" },
  { word: "livre", clue: "Ensemble de pages imprimées et reliées" },
  { word: "montagne", clue: "Élévation naturelle du terrain" },
  { word: "rivière", clue: "Cours d'eau naturel" },
  { word: "ordinateur", clue: "Machine pour traiter l'information" },
  { word: "téléphone", clue: "Appareil pour communiquer à distance" },
  { word: "voiture", clue: "Véhicule automobile à quatre roues" },
  { word: "maison", clue: "Bâtiment servant d'habitation" },
  { word: "arbre", clue: "Végétal avec un tronc et des branches" },
  { word: "fleur", clue: "Partie colorée et odorante d'une plante" },
  { word: "plage", clue: "Étendue de sable au bord de la mer" },
  { word: "ciel", clue: "Espace visible au-dessus de la Terre" },
  { word: "étoile", clue: "Astre qui brille dans la nuit" },
  { word: "lune", clue: "Satellite naturel de notre planète" },
  { word: "cuisine", clue: "Pièce où l'on prépare les repas" },
  { word: "chaise", clue: "Siège avec un dossier pour une personne" },
  { word: "table", clue: "Meuble pour manger ou travailler" },
  { word: "fourchette", clue: "Couvert pour piquer les aliments" },
  { word: "couteau", clue: "Ustensile tranchant pour couper" },
  { word: "verre", clue: "Récipient transparent pour boire" },
  { word: "fenêtre", clue: "Ouverture vitrée dans un mur" },
  { word: "porte", clue: "Panneau mobile pour fermer une ouverture" },
  { word: "lit", clue: "Meuble sur lequel on dort" },
  { word: "rêve", clue: "Histoire que l'on se fait en dormant" },
  { word: "amour", clue: "Sentiment d'affection très fort" },
  { word: "amitié", clue: "Lien d'affection entre personnes" },
  { word: "famille", clue: "Ensemble des parents et enfants" },
  { word: "travail", clue: "Activité professionnelle rémunérée" },
  { word: "école", clue: "Lieu où l'on apprend" },
  { word: "vacances", clue: "Période de repos, sans travail" },
  { word: "sport", clue: "Activité physique et de loisir" },
  { word: "cinéma", clue: "Art de faire des films" },
  { word: "théâtre", clue: "Lieu de représentation de pièces" },
  { word: "danse", clue: "Mouvement du corps en rythme" },
  { word: "peinture", clue: "Art d'appliquer des couleurs" },
  { word: "sculpture", clue: "Art de modeler ou tailler la matière" },
  { word: "poésie", clue: "Art du langage et des vers" },
  { word: "forêt", clue: "Grande étendue couverte d'arbres" },
  { word: "désert", clue: "Région aride avec peu de végétation" },
  { word: "océan", clue: "Vaste étendue d'eau salée" },
  { word: "île", clue: "Terre entourée d'eau" },
  { word: "volcan", clue: "Montagne qui crache du feu" },
  { word: "grotte", clue: "Cavité naturelle dans la roche" },
  { word: "cascade", clue: "Chute d'eau naturelle" },
  { word: "brouillard", clue: "Nuage très bas qui touche le sol" },
  { word: "neige", clue: "Précipitation de cristaux de glace" },
  { word: "orage", clue: "Perturbation avec éclairs et tonnerre" },
  { word: "arc-en-ciel", clue: "Phénomène optique après la pluie" },
  { word: "planète", clue: "Astre en orbite autour d'une étoile" },
  { word: "galaxie", clue: "Ensemble de milliards d'étoiles" },
  { word: "cerveau", clue: "Organe de la pensée" },
  { word: "cœur", clue: "Organe qui pompe le sang" },
  { word: "main", clue: "Partie du corps pour saisir" },
  { word: "œil", clue: "Organe de la vision" },
  { word: "sourire", clue: "Expression de joie du visage" },
  { word: "rire", clue: "Son exprimant la gaieté" },
  { word: "larme", clue: "Goutte d'eau salée de l'œil" },
  { word: "silence", clue: "Absence de bruit" },
  { word: "temps", clue: "Ce qui passe, les heures, les jours..." },
  { word: "histoire", clue: "Récit d'événements passés" },
  { word: "futur", clue: "Ce qui n'est pas encore arrivé" },
  { word: "liberté", clue: "État de ne pas être contraint" },
  { word: "paix", clue: "Absence de guerre ou de conflit" },
  { word: "guerre", clue: "Lutte armée entre États" },
  { word: "pont", clue: "Construction pour franchir un obstacle" },
  { word: "route", clue: "Voie aménagée pour la circulation" },
  { word: "train", clue: "Moyen de transport sur rails" },
  { word: "avion", clue: "Appareil qui vole dans les airs" },
  { word: "bateau", clue: "Construction flottante pour naviguer" },
  { word: "vélo", clue: "Moyen de transport à deux roues" },
  { word: "miroir", clue: "Surface qui réfléchit l'image" },
  { word: "bouteille", clue: "Récipient pour les liquides" },
  { word: "assiette", clue: "Pièce de vaisselle pour manger" },
  { word: "canapé", clue: "Long siège confortable pour plusieurs" },
  { word: "lampe", clue: "Appareil qui produit de la lumière" },
  { word: "tapis", clue: "Ouvrage textile qui couvre le sol" },
  { word: "rideau", clue: "Pièce de tissu devant une fenêtre" },
  { word: "escalier", clue: "Série de marches pour changer d'étage" },
  { word: "toit", clue: "Couverture supérieure d'un bâtiment" },
  { word: "mur", clue: "Paroi verticale d'une construction" },
  { word: "sol", clue: "Surface sur laquelle on marche" },
  { word: "plafond", clue: "Surface supérieure d'une pièce" },
  { word: "jambe", clue: "Membre inférieur du corps humain" },
  { word: "bras", clue: "Membre supérieur du corps humain" },
  { word: "cheveu", clue: "Poil qui pousse sur la tête" },
  { word: "dent", clue: "Organe dur dans la bouche pour mâcher" },
  { word: "langue", clue: "Organe mobile dans la bouche" },
  { word: "nez", clue: "Partie du visage pour sentir et respirer" },
  { word: "oreille", clue: "Organe de l'ouïe" },
  { word: "peau", clue: "Enveloppe extérieure du corps" },
  { word: "sang", clue: "Liquide rouge qui circule dans le corps" },
  { word: "muscle", clue: "Tissu qui produit le mouvement" },
  { word: "os", clue: "Partie dure du squelette" },
  { word: "doigt", clue: "Partie articulée de la main" },
  { word: "pied", clue: "Extrémité de la jambe pour marcher" },
  { word: "genou", clue: "Articulation au milieu de la jambe" },
  { word: "coude", clue: "Articulation au milieu du bras" },
  { word: "épaule", clue: "Articulation qui relie le bras au tronc" },
  { word: "ventre", clue: "Partie avant du corps sous la poitrine" },
  { word: "dos", clue: "Partie arrière du corps humain" },
  { word: "tête", clue: "Partie supérieure du corps avec le cerveau" },
  { word: "visage", clue: "Partie avant de la tête" },
  { word: "lèvre", clue: "Bord charnu de la bouche" },
  { word: "sourcil", clue: "Arc de poils au-dessus de l'œil" },
  { word: "cil", clue: "Poil au bord de la paupière" },
  { word: "front", clue: "Partie supérieure du visage" },
  { word: "menton", clue: "Partie inférieure du visage" },
  { word: "joue", clue: "Partie latérale du visage" },
  { word: "cou", clue: "Partie qui relie la tête au corps" },
  { word: "poignet", clue: "Articulation entre la main et l'avant-bras" },
  { word: "cheville", clue: "Articulation entre le pied et la jambe" },
  { word: "vêtement", clue: "Ce qui sert à habiller" },
  { word: "chemise", clue: "Vêtement à manches pour le haut du corps" },
  { word: "pantalon", clue: "Vêtement qui couvre les jambes" },
  { word: "robe", clue: "Vêtement féminin d'une seule pièce" },
  { word: "jupe", clue: "Vêtement féminin qui couvre les jambes" },
  { word: "chaussure", clue: "Ce que l'on met aux pieds pour marcher" },
  { word: "chapeau", clue: "Couvre-chef" },
  { word: "manteau", clue: "Vêtement chaud pour l'extérieur" },
  { word: "écharpe", clue: "Bande de tissu portée autour du cou" },
  { word: "gant", clue: "Accessoire qui couvre la main" },
  { word: "ceinture", clue: "Bande qui se porte à la taille" },
  { word: "lunettes", clue: "Instrument d'optique pour mieux voir" },
  { word: "montre", clue: "Instrument qui donne l'heure" },
  { word: "sac", clue: "Objet pour transporter des affaires" },
  { word: "bijou", clue: "Objet de parure précieux" },
  { word: "bague", clue: "Anneau porté au doigt" },
  { word: "collier", clue: "Bijou porté autour du cou" },
  { word: "bracelet", clue: "Bijou porté au poignet" },
  { word: "boucle", clue: "Ornement d'oreille" },
  { word: "animal", clue: "Être vivant, non végétal" },
  { word: "chien", clue: "Animal domestique, meilleur ami de l'homme" },
  { word: "chat", clue: "Félin domestique" },
  { word: "cheval", clue: "Grand mammifère herbivore" },
  { word: "vache", clue: "Femelle du taureau, produit du lait" },
  { word: "mouton", clue: "Animal élevé pour sa laine" },
  { word: "cochon", clue: "Animal de la ferme rose" },
  { word: "poule", clue: "Volaille qui pond des œufs" },
  { word: "canard", clue: "Oiseau aquatique" },
  { word: "lapin", clue: "Petit mammifère aux longues oreilles" },
  { word: "souris", clue: "Petit rongeur" },
  { word: "lion", clue: "Grand félin, roi de la savane" },
  { word: "tigre", clue: "Grand félin à rayures" },
  { word: "ours", clue: "Grand mammifère omnivore" },
  { word: "loup", clue: "Canidé sauvage qui vit en meute" },
  { word: "renard", clue: "Canidé rusé à la queue touffue" },
  { word: "singe", clue: "Primate qui vit dans les arbres" },
  { word: "éléphant", clue: "Plus grand mammifère terrestre" },
  { word: "girafe", clue: "Animal au très long cou" },
  { word: "zèbre", clue: "Équidé à rayures noires et blanches" },
  { word: "hippopotame", clue: "Grand mammifère semi-aquatique" },
  { word: "crocodile", clue: "Grand reptile carnivore" },
  { word: "serpent", clue: "Reptile sans pattes" },
  { word: "lézard", clue: "Petit reptile à quatre pattes" },
  { word: "tortue", clue: "Reptile avec une carapace" },
  { word: "grenouille", clue: "Amphibien qui coasse" },
  { word: "poisson", clue: "Animal aquatique avec des nageoires" },
  { word: "requin", clue: "Grand poisson carnivore" },
  { word: "baleine", clue: "Très grand mammifère marin" },
  { word: "dauphin", clue: "Mammifère marin intelligent" },
  { word: "phoque", clue: "Mammifère marin aux pattes palmées" },
  { word: "pingouin", clue: "Oiseau marin qui ne vole pas" },
  { word: "aigle", clue: "Grand oiseau de proie" },
  { word: "hibou", clue: "Oiseau de proie nocturne" },
  { word: "pigeon", clue: "Oiseau commun des villes" },
  { word: "moineau", clue: "Petit oiseau commun" },
  { word: "perroquet", clue: "Oiseau coloré qui peut parler" },
  { word: "cygne", clue: "Grand oiseau aquatique blanc" },
  { word: "insecte", clue: "Petit animal à six pattes" },
  { word: "fourmi", clue: "Insecte qui vit en colonie" },
  { word: "abeille", clue: "Insecte qui produit du miel" },
  { word: "papillon", clue: "Insecte aux grandes ailes colorées" },
  { word: "coccinelle", clue: "Insecte rouge à points noirs" },
  { word: "moustique", clue: "Insecte qui pique" },
  { word: "araignée", clue: "Arachnide à huit pattes" },
  { word: "mouche", clue: "Insecte volant commun" },
  { word: "libellule", clue: "Insecte aux longues ailes transparentes" },
  { word: "fruit", clue: "Aliment sucré qui pousse sur les plantes" },
  { word: "légume", clue: "Plante ou partie de plante potagère" },
  { word: "pomme", clue: "Fruit rond et croquant" },
  { word: "banane", clue: "Fruit jaune et allongé" },
  { word: "orange", clue: "Agrume de couleur vive" },
  { word: "fraise", clue: "Petit fruit rouge et sucré" },
  { word: "cerise", clue: "Petit fruit rouge à noyau" },
  { word: "raisin", clue: "Fruit qui pousse en grappes" },
  { word: "pêche", clue: "Fruit juteux à la peau duveteuse" },
  { word: "abricot", clue: "Fruit orange et velouté" },
  { word: "poire", clue: "Fruit en forme de goutte" },
  { word: "ananas", clue: "Fruit tropical à l'écorce rugueuse" },
  { word: "mangue", clue: "Fruit tropical à la chair orange" },
  { word: "kiwi", clue: "Fruit à la peau brune et à la chair verte" },
  { word: "citron", clue: "Agrume acide et jaune" },
  { word: "tomate", clue: "Fruit souvent utilisé comme légume" },
  { word: "carotte", clue: "Légume racine orange" },
  { word: "salade", clue: "Plante à feuilles vertes mangée crue" },
  { word: "pomme de terre", clue: "Tubercule très consommé" },
  { word: "oignon", clue: "Légume bulbe qui fait pleurer" },
  { word: "ail", clue: "Condiment à gousses au goût prononcé" },
  { word: "courgette", clue: "Légume vert et allongé" },
  { word: "aubergine", clue: "Légume violet" },
  { word: "poivron", clue: "Légume de différentes couleurs (vert, rouge, jaune)" },
  { word: "champignon", clue: "Fungus comestible" },
  { word: "brocoli", clue: "Légume vert en forme de petit arbre" },
  { word: "chou-fleur", clue: "Légume blanc en forme de fleur" },
  { word: "épinard", clue: "Légume à feuilles vertes riche en fer" },
  { word: "petit pois", clue: "Petite graine verte dans une cosse" },
  { word: "haricot", clue: "Graine ou gousse comestible" },
  { word: "maïs", clue: "Céréale aux grains jaunes" },
  { word: "pain", clue: "Aliment de base fait de farine et d'eau" },
  { word: "riz", clue: "Céréale cultivée dans les régions chaudes" },
  { word: "pâtes", clue: "Aliment à base de semoule de blé dur" },
  { word: "sucre", clue: "Substance douce extraite de la canne ou betterave" },
  { word: "sel", clue: "Condiment pour relever le goût" },
  { word: "poivre", clue: "Épice qui pique" },
  { word: "huile", clue: "Matière grasse liquide" },
  { word: "vinaigre", clue: "Liquide acide pour l'assaisonnement" },
  { word: "moutarde", clue: "Condiment jaune et piquant" },
  { word: "ketchup", clue: "Sauce à base de tomates" },
  { word: "mayonnaise", clue: "Sauce à base d'huile et de jaune d'œuf" },
  { word: "beurre", clue: "Matière grasse issue du lait" },
  { word: "crème", clue: "Partie grasse du lait" },
  { word: "yaourt", clue: "Lait fermenté" },
  { word: "œuf", clue: "Produit par la poule, se mange" },
  { word: "viande", clue: "Chair des animaux" },
  { word: "poulet", clue: "Volaille à chair blanche" },
  { word: "bœuf", clue: "Viande de vache ou de taureau" },
  { word: "porc", clue: "Viande de cochon" },
  { word: "agneau", clue: "Viande de jeune mouton" },
  { word: "poisson", clue: "Chair d'animal aquatique" },
  { word: "crevette", clue: "Petit crustacé marin" },
  { word: "moule", clue: "Coquillage noir" },
  { word: "huître", clue: "Coquillage que l'on mange cru" },
  { word: "eau", clue: "Liquide transparent indispensable à la vie" },
  { word: "jus", clue: "Boisson extraite des fruits ou légumes" },
  { word: "lait", clue: "Liquide blanc nutritif" },
  { word: "thé", clue: "Boisson par infusion de feuilles" },
  { word: "café", clue: "Boisson stimulante à base de grains torréfiés" },
  { word: "vin", clue: "Boisson alcoolisée issue du raisin" },
  { word: "bière", clue: "Boisson alcoolisée à base de malt et de houblon" },
  { word: "couleur", clue: "Sensation visuelle (rouge, bleu...)" },
  { word: "rouge", clue: "Couleur du sang, de la tomate" },
  { word: "bleu", clue: "Couleur du ciel, de la mer" },
  { word: "jaune", clue: "Couleur du soleil, du citron" },
  { word: "vert", clue: "Couleur de l'herbe, des feuilles" },
  { word: "orange", clue: "Couleur du fruit du même nom" },
  { word: "violet", clue: "Mélange de rouge et de bleu" },
  { word: "rose", clue: "Couleur de la fleur du même nom" },
  { word: "marron", clue: "Couleur de la terre, du bois" },
  { word: "noir", clue: "Couleur la plus sombre, absence de lumière" },
  { word: "blanc", clue: "Couleur de la neige, du lait" },
  { word: "gris", clue: "Mélange de noir et de blanc" },
  { word: "nombre", clue: "Concept mathématique pour compter" },
  { word: "lettre", clue: "Signe graphique d'un alphabet" },
  { word: "mot", clue: "Ensemble de lettres formant un sens" },
  { word: "phrase", clue: "Ensemble de mots formant un sens complet" },
  { word: "texte", clue: "Ensemble de phrases formant un écrit" },
  { word: "stylo", clue: "Instrument pour écrire" },
  { word: "crayon", clue: "Instrument d'écriture à mine de graphite" },
  { word: "gomme", clue: "Objet pour effacer" },
  { word: "papier", clue: "Support pour écrire ou dessiner" },
  { word: "cahier", clue: "Ensemble de feuilles de papier reliées" },
  { word: "cartable", clue: "Sac d'écolier" },
  { word: "classe", clue: "Salle de cours dans une école" },
  { word: "professeur", clue: "Personne qui enseigne" },
  { word: "élève", clue: "Personne qui apprend à l'école" },
  { word: "devoir", clue: "Travail à faire pour l'école" },
  { word: "leçon", clue: "Ce qui est enseigné" },
  { word: "examen", clue: "Épreuve pour évaluer les connaissances" },
  { word: "note", clue: "Appréciation d'un travail scolaire" },
  { word: "diplôme", clue: "Titre qui atteste d'un niveau d'études" },
  { word: "université", clue: "Établissement d'enseignement supérieur" },
  { word: "métier", clue: "Profession, travail habituel" },
  { word: "médecin", clue: "Personne qui soigne les malades" },
  { word: "infirmier", clue: "Personne qui assiste le médecin" },
  { word: "pompier", clue: "Personne qui éteint les incendies" },
  { word: "policier", clue: "Agent de la force publique" },
  { word: "boulanger", clue: "Personne qui fait le pain" },
  { word: "pâtissier", clue: "Personne qui fait des gâteaux" },
  { word: "cuisinier", clue: "Personne qui prépare les repas" },
  { word: "serveur", clue: "Personne qui sert dans un restaurant" },
  { word: "vendeur", clue: "Personne qui vend dans un magasin" },
  { word: "caissier", clue: "Personne qui encaisse l'argent" },
  { word: "coiffeur", clue: "Personne qui coupe les cheveux" },
  { word: "maçon", clue: "Personne qui construit les murs" },
  { word: "plombier", clue: "Personne qui installe/répare la tuyauterie" },
  { word: "électricien", clue: "Personne qui installe l'électricité" },
  { word: "mécanicien", clue: "Personne qui répare les voitures" },
  { word: "pilote", clue: "Personne qui conduit un avion" },
  { word: "chauffeur", clue: "Personne qui conduit un véhicule" },
  { word: "acteur", clue: "Personne qui joue un rôle (cinéma, théâtre)" },
  { word: "chanteur", clue: "Personne dont le métier est de chanter" },
  { word: "musicien", clue: "Personne qui joue d'un instrument" },
  { word: "danseur", clue: "Personne dont le métier est de danser" },
  { word: "peintre", clue: "Artiste qui pratique la peinture" },
  { word: "sculpteur", clue: "Artiste qui pratique la sculpture" },
  { word: "écrivain", clue: "Personne qui écrit des livres" },
  { word: "journaliste", clue: "Personne qui informe sur l'actualité" },
  { word: "photographe", clue: "Personne qui prend des photos" },
  { word: "avocat", clue: "Personne qui défend en justice" },
  { word: "juge", clue: "Personne qui rend la justice" },
  { word: "architecte", clue: "Personne qui conçoit les bâtiments" },
  { word: "ingénieur", clue: "Personne qui résout des problèmes techniques" },
  { word: "scientifique", clue: "Personne qui fait de la recherche" },
  { word: "astronaute", clue: "Personne qui voyage dans l'espace" },
  { word: "agriculteur", clue: "Personne qui cultive la terre" },
  { word: "vétérinaire", clue: "Médecin pour les animaux" }
];
